var Conference = require("./Conference");

/**
 * Creates new connection object for the Jitsi Meet server side video conferencing service.
 * @param appID identification for the provider of Jitsi Meet video conferencing services.
 * @param token secret generated by the provider of Jitsi Meet video conferencing services.
 * The token will be send to the provider from the Jitsi Meet server deployment for authorization of the current client.
 * @param options Object with properties / settings related to connection with the server.
 * @constructor
 */
function Connection(appID, token, options) {

}

/**
 * This method allows renewal of the tokens if they are expiring.
 * @param token the new token.
 */
Connection.prototype.setToken = function (token) {

}

/**
 * Connect the client with the server.
 * @param successCallback this callback will be called when the connection is successfull
 * @param errorCallback this callback will be called when the connection fail.
 */
Connection.prototype.connect = function (successCallback, errorCallback) {

}

/**
 * Creates and joins new conference.
 * @param name the name of the conference
 * @param options Object with properties / settings related to the conference that will be created.
 * @returns {Conference} returns the new conference object.
 */
Connection.prototype.initConference = function (name, options) {
    return new Conference();
}

module.exports = Connection;